FROM node:20-slim

# Install Chromium and dependencies for Puppeteer
RUN apt-get update && apt-get install -y \
    chromium \
    fonts-liberation \
    fonts-noto-cjk \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libgdk-pixbuf2.0-0 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    xdg-utils \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Set Puppeteer environment variables
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies (NODE_ENV not yet set to production, so devDependencies
# like typescript/@types/* install too — needed for the build step below)
RUN npm ci

# Copy source code
COPY . .

# Prisma Client has a custom output path (prisma/generated/prisma, see
# schema.prisma) and isn't generated by `npm ci` automatically — without this,
# the build below fails with "Cannot find module '.../prisma/generated/prisma'"
RUN npx prisma generate

# Build TypeScript
RUN npm run build

# Create storage directories
RUN mkdir -p storage/generated storage/templates storage/whatsapp

# Set after install+build so it only affects the running app, not `npm ci`
ENV NODE_ENV=production

# Expose the fixed production port
EXPOSE 5090

# Start application
CMD ["node", "dist/server.js"]
